name: R-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Specify the OS in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Define both Ubuntu and Windows as OS options
        r-version: ['release', '4.2.3']  # Use release for latest R version and a specific older one

    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up the R environment with the specified R versions
      - name: Set up R ${{ matrix.r-version }} on ${{ matrix.os }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Step 3: Install dependencies (remotes, rcmdcheck)
      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Step 4: Run R CMD check on the package
      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
